In [1]:
import numpy as np
import pandas as pd

In [2]:
a = pd.Series(list('abcdef'))
a

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object

In [3]:
np_country = np.array(['luxembourg','Norway','Japan','Switzerland','United States','Qatar','Iceland',
                       'Sweden','Singapore','Denmark'])
np_country

array(['luxembourg', 'Norway', 'Japan', 'Switzerland', 'United States',
       'Qatar', 'Iceland', 'Sweden', 'Singapore', 'Denmark'], dtype='<U13')

In [4]:
series_country = pd.Series(np_country)
series_country

0       luxembourg
1           Norway
2            Japan
3      Switzerland
4    United States
5            Qatar
6          Iceland
7           Sweden
8        Singapore
9          Denmark
dtype: object

In [5]:
data_series = {"column1" : pd.Series([10,20,30,40,50]),
               "column2" : pd.Series([100,200,300,400,500])
              }
print(data_series)

{'column1': 0    10
1    20
2    30
3    40
4    50
dtype: int64, 'column2': 0    100
1    200
2    300
3    400
4    500
dtype: int64}

In [6]:
pd.DataFrame(data_series)

   column1  column2
0       10      100
1       20      200
2       30      300
3       40      400
4       50      500

In [7]:
country_happiness = pd.Series([7.809, 7.646, 7.560, 7.504, 7.488, 7.449, 7.353, 7.3, 7.294, 7.238],
                             index = ['Finland','Denmark','Switzerland','Iceland','Norway',
                                      'Netherlands','Sweden','NewZealand','Austria','Luxembourg'])
country_happiness

Finland        7.809
Denmark        7.646
Switzerland    7.560
Iceland        7.504
Norway         7.488
Netherlands    7.449
Sweden         7.353
NewZealand     7.300
Austria        7.294
Luxembourg     7.238
dtype: float64

In [8]:
country_happiness.index

Index(['Finland', 'Denmark', 'Switzerland', 'Iceland', 'Norway', 'Netherlands',
       'Sweden', 'NewZealand', 'Austria', 'Luxembourg'],
      dtype='object')

In [9]:
country_happiness.values

array([7.809, 7.646, 7.56 , 7.504, 7.488, 7.449, 7.353, 7.3  , 7.294,
       7.238])

In [10]:
country_happiness[0:5]

Finland        7.809
Denmark        7.646
Switzerland    7.560
Iceland        7.504
Norway         7.488
dtype: float64

In [11]:
autoprice = pd.read_csv('Automobile_price_data__Raw_.csv')
display(autoprice)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [12]:
autoprice.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [13]:
autoprice.tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [14]:
autoprice.shape

(205, 26)

In [15]:
autoprice.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [16]:
for i,j in autoprice.iterrows():
    print(i,j)

0 symboling                      3
normalized-losses              ?
make                 alfa-romero
fuel-type                    gas
aspiration                   std
num-of-doors                 two
body-style           convertible
drive-wheels                 rwd
engine-location            front
wheel-base                  88.6
length                     168.8
width                       64.1
height                      48.8
curb-weight                 2548
engine-type                 dohc
num-of-cylinders            four
engine-size                  130
fuel-system                 mpfi
bore                        3.47
stroke                      2.68
compression-ratio            9.0
horsepower                   111
peak-rpm                    5000
city-mpg                      21
highway-mpg                   27
price                      13495
Name: 0, dtype: object
1 symboling                      3
normalized-losses              ?
make                 alfa-romero
fuel-type                    gas
aspiration                   std
num-of-doors                 two
body-style           convertible
drive-wheels                 rwd
engine-location            front
wheel-base                  88.6
length                     168.8
width                       64.1
height                      48.8
curb-weight                 2548
engine-type                 dohc
num-of-cylinders            four
engine-size                  130
fuel-system                 mpfi
bore                        3.47
stroke                      2.68
compression-ratio            9.0
horsepower                   111
peak-rpm                    5000
city-mpg                      21
highway-mpg                   27
price                      16500
Name: 1, dtype: object
2 symboling                      1
normalized-losses              ?
make                 alfa-romero
fuel-type                    gas
aspiration                   std
num-of-doors                 two
body-style             hatchback
drive-wheels                 rwd
engine-location            front
wheel-base                  94.5
length                     171.2
width                       65.5
height                      52.4
curb-weight                 2823
engine-type                 ohcv
num-of-cylinders             six
engine-size                  152
fuel-system                 mpfi
bore                        2.68
stroke                      3.47
compression-ratio            9.0
horsepower                   154
peak-rpm                    5000
city-mpg                      19
highway-mpg                   26
price                      16500
Name: 2, dtype: object
3 symboling                2
normalized-losses      164
make                  audi
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           fwd
engine-location      front
wheel-base            99.8
length               176.6
width                 66.2
height                54.3
curb-weight           2337
engine-type            ohc
num-of-cylinders      four
engine-size            109
fuel-system           mpfi
bore                  3.19
stroke                3.40
compression-ratio     10.0
horsepower             102
peak-rpm              5500
city-mpg                24
highway-mpg             30
price                13950
Name: 3, dtype: object
4 symboling                2
normalized-losses      164
make                  audi
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           4wd
engine-location      front
wheel-base            99.4
length               176.6
width                 66.4
height                54.3
curb-weight           2824
engine-type            ohc
num-of-cylinders      five
engine-size            136
fuel-system           mpfi
bore                  3.19
stroke                3.40
compression-ratio      8.0
horsepower             115
peak-rpm              5500
city-mpg                18
highway-mpg             22
price                17450
Name: 4, dtype: object
5 symboling                2
normalized-losses        ?
make                  audi
fuel-type              gas
aspiration             std
num-of-doors           two
body-style           sedan
drive-wheels           fwd
engine-location      front
wheel-base            99.8
length               177.3
width                 66.3
height                53.1
curb-weight           2507
engine-type            ohc
num-of-cylinders      five
engine-size            136
fuel-system           mpfi
bore                  3.19
stroke                3.40
compression-ratio      8.5
horsepower             110
peak-rpm              5500
city-mpg                19
highway-mpg             25
price                15250
Name: 5, dtype: object
6 symboling                1
normalized-losses      158
make                  audi
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           fwd
engine-location      front
wheel-base           105.8
length               192.7
width                 71.4
height                55.7
curb-weight           2844
engine-type            ohc
num-of-cylinders      five
engine-size            136
fuel-system           mpfi
bore                  3.19
stroke                3.40
compression-ratio      8.5
horsepower             110
peak-rpm              5500
city-mpg                19
highway-mpg             25
price                17710
Name: 6, dtype: object
7 symboling                1
normalized-losses        ?
make                  audi
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           wagon
drive-wheels           fwd
engine-location      front
wheel-base           105.8
length               192.7
width                 71.4
height                55.7
curb-weight           2954
engine-type            ohc
num-of-cylinders      five
engine-size            136
fuel-system           mpfi
bore                  3.19
stroke                3.40
compression-ratio      8.5
horsepower             110
peak-rpm              5500
city-mpg                19
highway-mpg             25
price                18920
Name: 7, dtype: object
8 symboling                1
normalized-losses      158
make                  audi
fuel-type              gas
aspiration           turbo
num-of-doors          four
body-style           sedan
drive-wheels           fwd
engine-location      front
wheel-base           105.8
length               192.7
width                 71.4
height                55.9
curb-weight           3086
engine-type            ohc
num-of-cylinders      five
engine-size            131
fuel-system           mpfi
bore                  3.13
stroke                3.40
compression-ratio      8.3
horsepower             140
peak-rpm              5500
city-mpg                17
highway-mpg             20
price                23875
Name: 8, dtype: object
9 symboling                    0
normalized-losses            ?
make                      audi
fuel-type                  gas
aspiration               turbo
num-of-doors               two
body-style           hatchback
drive-wheels               4wd
engine-location          front
wheel-base                99.5
length                   178.2
width                     67.9
height                    52.0
curb-weight               3053
engine-type                ohc
num-of-cylinders          five
engine-size                131
fuel-system               mpfi
bore                      3.13
stroke                    3.40
compression-ratio          7.0
horsepower                 160
peak-rpm                  5500
city-mpg                    16
highway-mpg                 22
price                        ?
Name: 9, dtype: object
10 symboling                2
normalized-losses      192
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors           two
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           101.2
length               176.8
width                 64.8
height                54.3
curb-weight           2395
engine-type            ohc
num-of-cylinders      four
engine-size            108
fuel-system           mpfi
bore                  3.50
stroke                2.80
compression-ratio      8.8
horsepower             101
peak-rpm              5800
city-mpg                23
highway-mpg             29
price                16430
Name: 10, dtype: object
11 symboling                0
normalized-losses      192
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           101.2
length               176.8
width                 64.8
height                54.3
curb-weight           2395
engine-type            ohc
num-of-cylinders      four
engine-size            108
fuel-system           mpfi
bore                  3.50
stroke                2.80
compression-ratio      8.8
horsepower             101
peak-rpm              5800
city-mpg                23
highway-mpg             29
price                16925
Name: 11, dtype: object
12 symboling                0
normalized-losses      188
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors           two
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           101.2
length               176.8
width                 64.8
height                54.3
curb-weight           2710
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                21
highway-mpg             28
price                20970
Name: 12, dtype: object
13 symboling                0
normalized-losses      188
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           101.2
length               176.8
width                 64.8
height                54.3
curb-weight           2765
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                21
highway-mpg             28
price                21105
Name: 13, dtype: object
14 symboling                1
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               189.0
width                 66.9
height                55.7
curb-weight           3055
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                20
highway-mpg             25
price                24565
Name: 14, dtype: object
15 symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               189.0
width                 66.9
height                55.7
curb-weight           3230
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                16
highway-mpg             22
price                30760
Name: 15, dtype: object
16 symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors           two
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               193.8
width                 67.9
height                53.7
curb-weight           3380
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                16
highway-mpg             22
price                41315
Name: 16, dtype: object
17 symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           110.0
length               197.0
width                 70.9
height                56.3
curb-weight           3505
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                15
highway-mpg             20
price                36880
Name: 17, dtype: object
18 symboling                    2
normalized-losses          121
make                 chevrolet
fuel-type                  gas
aspiration                 std
num-of-doors               two
body-style           hatchback
drive-wheels               fwd
engine-location          front
wheel-base                88.4
length                   141.1
width                     60.3
height                    53.2
curb-weight               1488
engine-type                  l
num-of-cylinders         three
engine-size                 61
fuel-system               2bbl
bore                      2.91
stroke                    3.03
compression-ratio          9.5
horsepower                  48
peak-rpm                  5100
city-mpg                    47
highway-mpg                 53
price                     5151
Name: 18, dtype: object
19 symboling                    1
normalized-losses           98
make                 chevrolet
fuel-type                  gas
aspiration                 std
num-of-doors               two
body-style           hatchback
drive-wheels               fwd
engine-location          front
wheel-base                94.5
length                   155.9
width                     63.6
height                    52.0
curb-weight               1874
engine-type                ohc
num-of-cylinders          four
engine-size                 90
fuel-system               2bbl
bore                      3.03
stroke                    3.11
compression-ratio          9.6
horsepower                  70
peak-rpm                  5400
city-mpg                    38
highway-mpg                 43
price                     6295
Name: 19, dtype: object
20 symboling                    0
normalized-losses           81
make                 chevrolet
fuel-type                  gas
aspiration                 std
num-of-doors              four
body-style               sedan
drive-wheels               fwd
engine-location          front
wheel-base                94.5
length                   158.8
width                     63.6
height                    52.0
curb-weight               1909
engine-type                ohc
num-of-cylinders          four
engine-size                 90
fuel-system               2bbl
bore                      3.03
stroke                    3.11
compression-ratio          9.6
horsepower                  70
peak-rpm                  5400
city-mpg                    38
highway-mpg                 43
price                     6575
Name: 20, dtype: object
21 symboling                    1
normalized-losses          118
make                     dodge
fuel-type                  gas
aspiration                 std
num-of-doors               two
body-style           hatchback
drive-wheels               fwd
engine-location          front
wheel-base                93.7
length                   157.3
width                     63.8
height                    50.8
curb-weight               1876
engine-type                ohc
num-of-cylinders          four
engine-size                 90
fuel-system               2bbl
bore                      2.97
stroke                    3.23
compression-ratio         9.41
horsepower                  68
peak-rpm                  5500
city-mpg                    37
highway-mpg                 41
price                     5572
Name: 21, dtype: object
22 symboling                    1
normalized-losses          118
make                     dodge
fuel-type                  gas
aspiration                 std
num-of-doors               two
body-style           hatchback
drive-wheels               fwd
engine-location          front
wheel-base                93.7
length                   157.3
width                     63.8
height                    50.8
curb-weight               1876
engine-type                ohc
num-of-cylinders          four
engine-size                 90
fuel-system               2bbl
bore                      2.97
stroke                    3.23
compression-ratio          9.4
horsepower                  68
peak-rpm                  5500
city-mpg                    31
highway-mpg                 38
price                     6377
Name: 22, dtype: object
23 symboling                    1
normalized-losses          118
make                     dodge
fuel-type                  gas
aspiration               turbo
num-of-doors               two
body-style           hatchback
drive-wheels               fwd
engine-location          front
wheel-base                93.7
length                   157.3
width                     63.8
height                    50.8
curb-weight               2128
engine-type                ohc
num-of-cylinders          four
engine-size                 98
fuel-system               mpfi
bore                      3.03
stroke                    3.39
compression-ratio          7.6
horsepower                 102
peak-rpm                  5500
city-mpg                    24
highway-mpg                 30
price                     7957
Name: 23, dtype: object
24 symboling                    1
normalized-losses          148
make                     dodge
fuel-type                  gas
aspiration                 std
num-of-doors              four
body-style           hatchback
drive-wheels               fwd
engine-location          front
wheel-base                93.7
length                   157.3
width                     63.8
height                    50.6
curb-weight               1967
engine-type                ohc
num-of-cylinders          four
engine-size                 90
fuel-system               2bbl
bore                      2.97
stroke                    3.23
compression-ratio          9.4
horsepower                  68
peak-rpm                  5500
city-mpg                    31
highway-mpg                 38
price                     6229
Name: 24, dtype: object
25 symboling                1
normalized-losses      148
make                 dodge
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           fwd
engine-location      front
wheel-base            93.7
length               157.3
width                 63.8
height                50.6
curb-weight           1989
engine-type            ohc
num-of-cylinders      four
engine-size             90
fuel-system           2bbl

In [17]:
autoprice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [18]:
autoprice.isnull()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
autoprice.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [20]:
autoprice_1 = autoprice.replace('?' , np.nan)
autoprice_1

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [21]:
autoprice_1.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [22]:
autoprice['engine-size'].sort_values()

18     61
57     70
55     70
56     70
32     79
     ...
48    258
47    258
74    304
73    308
49    326
Name: engine-size, Length: 205, dtype: int64

In [23]:
autoprice.sort_values(by = 'engine-size', ascending = True)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
57,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,13645
55,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,10945
56,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,11845
32,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,79,1bbl,2.91,3.07,10.1,60,5500,38,42,5399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,0,?,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,35550
47,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,32250
74,1,?,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.80,3.35,8.0,184,4500,14,16,45400
73,0,?,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,...,308,mpfi,3.80,3.35,8.0,184,4500,14,16,40960
49,0,?,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.5,262,5000,13,17,36000

In [24]:
autoprice.sort_values(by = 'city-mpg', ascending = False)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
30,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.6,58,4800,49,54,6479
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
90,1,128,nissan,diesel,std,two,sedan,fwd,front,94.5,...,103,idi,2.99,3.47,21.9,55,4800,45,50,7099
45,0,?,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?
32,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,79,1bbl,2.91,3.07,10.1,60,5500,38,42,5399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,32250
48,0,?,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,35550
73,0,?,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,...,308,mpfi,3.80,3.35,8.0,184,4500,14,16,40960
74,1,?,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.80,3.35,8.0,184,4500,14,16,45400
49,0,?,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.5,262,5000,13,17,36000

In [25]:
autoprice['engine-size'].unique()

array([130, 152, 109, 136, 131, 108, 164, 209,  61,  90,  98, 122, 156,
        92,  79, 110, 111, 119, 258, 326,  91,  70,  80, 140, 134, 183,
       234, 308, 304,  97, 103, 120, 181, 151, 194, 203, 132, 121, 146,
       171, 161, 141, 173, 145], dtype=int64)

In [26]:
autoprice[['engine-size','city-mpg','make']]

     engine-size  city-mpg         make
0            130        21  alfa-romero
1            130        21  alfa-romero
2            152        19  alfa-romero
3            109        24         audi
4            136        18         audi
..           ...       ...          ...
200          141        23        volvo
201          141        19        volvo
202          173        18        volvo
203          145        26        volvo
204          141        19        volvo

[205 rows x 3 columns]

In [28]:
autoprice['make'] == 'audi'

0      False
1      False
2      False
3       True
4       True
       ...
200    False
201    False
202    False
203    False
204    False
Name: make, Length: 205, dtype: bool

In [27]:
autoprice[autoprice['make'] == 'audi']

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

In [34]:
autoprice[(autoprice['make'] == 'audi')&(autoprice['num-of-doors'] == 'two')]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

In [35]:
autoprice[(autoprice['make'] == 'audi')|(autoprice['num-of-doors'] == 'two')]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161,5200,19,24,15998
182,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52,4800,37,46,7775
183,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,7975
189,3,?,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,11595
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,9980

In [40]:
autoprice[(autoprice['engine-size'] > 120 )&(autoprice['body-style'] == 'convertible')]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
72,3,142,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,...,234,mpfi,3.46,3.10,8.3,155,4750,16,18,35056
128,3,?,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207,5900,17,25,37028
172,2,134,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116,4800,24,30,17669

In [41]:
autoprice.loc[:,:]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [42]:
autoprice.loc[10:20,:]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
15,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
16,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
17,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6575

In [45]:
autoprice.loc[10:20,'make':'engine-size']

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size
10,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108
11,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108
12,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2710,ohc,six,164
13,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2765,ohc,six,164
14,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,3055,ohc,six,164
15,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,3230,ohc,six,209
16,bmw,gas,std,two,sedan,rwd,front,103.5,193.8,67.9,53.7,3380,ohc,six,209
17,bmw,gas,std,four,sedan,rwd,front,110.0,197.0,70.9,56.3,3505,ohc,six,209
18,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,60.3,53.2,1488,l,three,61
19,chevrolet,gas,std,two,hatchback,fwd,front,94.5,155.9,63.6,52.0,1874,ohc,four,90
20,chevrolet,gas,std,four,sedan,fwd,front,94.5,158.8,63.6,52.0,1909,ohc,four,90

In [46]:
autoprice.iloc[10:20,2:9]

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location
10,bmw,gas,std,two,sedan,rwd,front
11,bmw,gas,std,four,sedan,rwd,front
12,bmw,gas,std,two,sedan,rwd,front
13,bmw,gas,std,four,sedan,rwd,front
14,bmw,gas,std,four,sedan,rwd,front
15,bmw,gas,std,four,sedan,rwd,front
16,bmw,gas,std,two,sedan,rwd,front
17,bmw,gas,std,four,sedan,rwd,front
18,chevrolet,gas,std,two,hatchback,fwd,front
19,chevrolet,gas,std,two,hatchback,fwd,front

In [47]:
autoprice.iloc[10:20,::-1]

,price,highway-mpg,city-mpg,peak-rpm,horsepower,compression-ratio,stroke,bore,fuel-system,engine-size,...,wheel-base,engine-location,drive-wheels,body-style,num-of-doors,aspiration,fuel-type,make,normalized-losses,symboling
10,16430,29,23,5800,101,8.8,2.80,3.50,mpfi,108,...,101.2,front,rwd,sedan,two,std,gas,bmw,192,2
11,16925,29,23,5800,101,8.8,2.80,3.50,mpfi,108,...,101.2,front,rwd,sedan,four,std,gas,bmw,192,0
12,20970,28,21,4250,121,9.0,3.19,3.31,mpfi,164,...,101.2,front,rwd,sedan,two,std,gas,bmw,188,0
13,21105,28,21,4250,121,9.0,3.19,3.31,mpfi,164,...,101.2,front,rwd,sedan,four,std,gas,bmw,188,0
14,24565,25,20,4250,121,9.0,3.19,3.31,mpfi,164,...,103.5,front,rwd,sedan,four,std,gas,bmw,?,1
15,30760,22,16,5400,182,8.0,3.39,3.62,mpfi,209,...,103.5,front,rwd,sedan,four,std,gas,bmw,?,0
16,41315,22,16,5400,182,8.0,3.39,3.62,mpfi,209,...,103.5,front,rwd,sedan,two,std,gas,bmw,?,0
17,36880,20,15,5400,182,8.0,3.39,3.62,mpfi,209,...,110.0,front,rwd,sedan,four,std,gas,bmw,?,0
18,5151,53,47,5100,48,9.5,3.03,2.91,2bbl,61,...,88.4,front,fwd,hatchback,two,std,gas,chevrolet,121,2
19,6295,43,38,5400,70,9.6,3.11,3.03,2bbl,90,...,94.5,front,fwd,hatchback,two,std,gas,chevrolet,98,1

In [52]:
df_rand = autoprice.sample(n = 10)
df_rand

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
72,3,142,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,...,234,mpfi,3.46,3.10,8.30,155,4750,16,18,35056
75,1,?,mercury,gas,turbo,two,hatchback,rwd,front,102.7,...,140,mpfi,3.78,3.12,8.00,175,5000,19,24,16503
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92,2bbl,2.97,3.23,9.40,68,5500,31,38,6189
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151
31,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.20,76,6000,31,38,6855
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,24,28,15985
103,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.00,152,5200,19,25,13499
132,3,150,saab,gas,std,two,hatchback,fwd,front,99.1,...,121,mpfi,3.54,3.07,9.31,110,5250,21,28,11850
153,0,77,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.00,62,4800,31,37,6918
130,0,?,renault,gas,std,four,wagon,fwd,front,96.1,...,132,mpfi,3.46,3.90,8.70,?,?,23,31,9295

In [51]:
df_rand = autoprice.sample(frac = 0.2)
df_rand

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
35,0,110,honda,gas,std,four,sedan,fwd,front,96.5,...,92,1bbl,2.91,3.41,9.2,76,6000,30,34,7295
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6692
70,-1,93,mercedes-benz,diesel,turbo,four,sedan,rwd,front,115.6,...,183,idi,3.58,3.64,21.5,123,4350,22,25,31600
23,1,118,dodge,gas,turbo,two,hatchback,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.6,102,5500,24,30,7957
181,-1,?,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156,5200,19,24,15750
24,1,148,dodge,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6229
57,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,13645
164,1,168,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.0,70,4800,29,34,8238
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
47,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,32250
17,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
56,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,11845
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625
110,0,?,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95,4150,25,25,13860
86,1,125,mitsubishi,gas,std,four,sedan,fwd,front,96.3,...,122,2bbl,3.35,3.46,8.5,88,5000,25,32,8189
157,0,91,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70,4800,30,37,7198
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
76,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92,2bbl,2.97,3.23,9.4,68,5500,37,41,5389
144,0,102,subaru,gas,std,four,sedan,4wd,front,97.0,...,108,2bbl,3.62,2.64,9.0,82,4800,24,25,9233
131,2,?,renault,gas,std,two,hatchback,fwd,front,96.1,...,132,mpfi,3.46,3.90,8.7,?,?,23,31,9895
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
134,3,150,saab,gas,std,two,hatchback,fwd,front,99.1,...,121,mpfi,2.54,2.07,9.3,110,5250,21,28,15040
62,0,115,mazda,gas,std,four,sedan,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10245
146,0,89,subaru,gas,std,four,wagon,fwd,front,97.0,...,108,2bbl,3.62,2.64,9.0,82,4800,28,32,7463
75,1,?,mercury,gas,turbo,two,hatchback,rwd,front,102.7,...,140,mpfi,3.78,3.12,8.0,175,5000,19,24,16503
59,1,129,mazda,gas,std,two,hatchback,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,8845
74,1,?,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.80,3.35,8.0,184,4500,14,16,45400
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
29,3,145,dodge,gas,turbo,two,hatchback,fwd,front,95.9,...,156,mfi,3.60,3.90,7.0,145,5000,19,24,12964
72,3,142,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,...,234,mpfi,3.46,3.10,8.3,155,4750,16,18,35056
127,3,?,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207,5900,17,25,34028
166,1,168,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112,6600,26,29,9538
69,0,93,mercedes-benz,diesel,turbo,two,hardtop,rwd,front,106.7,...,183,idi,3.58,3.64,21.5,123,4350,22,25,28176
101,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
90,1,128,nissan,diesel,std,two,sedan,fwd,front,94.5,...,103,idi,2.99,3.47,21.9,55,4800,45,50,7099
61,1,129,mazda,gas,std,two,hatchback,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10595

In [53]:
autoprice.query("make == 'toyota' and `engine-size` > 100 and `drive-wheels` == 'fwd'")

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
158,0,91,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56,4500,34,36,7898
159,0,91,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56,4500,38,47,7788
173,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,29,34,8948
174,-1,65,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.5,73,4500,30,33,10698
175,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,27,32,9988
176,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,27,32,10898
177,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,27,32,11248

In [54]:
autoprice.drop([2,3,4,5,6,8,9,10], axis = 0)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [55]:
autoprice.drop(['symboling','normalized-losses'], axis = 1)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [56]:
autoprice.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
200    False
201    False
202    False
203    False
204    False
Length: 205, dtype: bool

In [57]:
autoprice[autoprice.duplicated()]

Empty DataFrame
Columns: [symboling, normalized-losses, make, fuel-type, aspiration, num-of-doors, body-style, drive-wheels, engine-location, wheel-base, length, width, height, curb-weight, engine-type, num-of-cylinders, engine-size, fuel-system, bore, stroke, compression-ratio, horsepower, peak-rpm, city-mpg, highway-mpg, price]
Index: []

[0 rows x 26 columns]

In [58]:
autoprice.drop_duplicates(inplace = True)

In [59]:
autoprice.groupby(['make'])

In [61]:
autoprice.groupby(['make']).first()

,symboling,normalized-losses,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
make,,,,,,,,,,,,,,,,,,,,,
alfa-romero,3,?,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
audi,2,164,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.00,102,5500,24,30,13950
bmw,2,192,gas,std,two,sedan,rwd,front,101.2,176.8,...,108,mpfi,3.50,2.80,8.80,101,5800,23,29,16430
chevrolet,2,121,gas,std,two,hatchback,fwd,front,88.4,141.1,...,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151
dodge,1,118,gas,std,two,hatchback,fwd,front,93.7,157.3,...,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572
honda,2,137,gas,std,two,hatchback,fwd,front,86.6,144.6,...,92,1bbl,2.91,3.41,9.60,58,4800,49,54,6479
isuzu,0,?,gas,std,four,sedan,rwd,front,94.3,170.7,...,111,2bbl,3.31,3.23,8.50,78,4800,24,29,6785
jaguar,0,145,gas,std,four,sedan,rwd,front,113.0,199.6,...,258,mpfi,3.63,4.17,8.10,176,4750,15,19,32250
mazda,1,104,gas,std,two,hatchback,fwd,front,93.1,159.1,...,91,2bbl,3.03,3.15,9.00,68,5000,30,31,5195
mercedes-benz,-1,93,diesel,turbo,four,sedan,rwd,front,110.0,190.9,...,183,idi,3.58,3.64,21.50,123,4350,22,25,25552
mercury,1,?,gas,turbo,two,hatchback,rwd,front,102.7,178.4,...,140,mpfi,3.78,3.12,8.00,175,5000,19,24,16503
mitsubishi,2,161,gas,std,two,hatchback,fwd,front,93.7,157.3,...,92,2bbl,2.97,3.23,9.40,68,5500,37,41,5389
nissan,1,128,gas,std,two,sedan,fwd,front,94.5,165.3,...,97,2bbl,3.15,3.29,9.40,69,5200,31,37,5499
peugot,0,161,gas,std,four,sedan,rwd,front,107.9,186.7,...,120,mpfi,3.46,3.19,8.40,97,5000,19,24,11900
plymouth,1,119,gas,std,two,hatchback,fwd,front,93.7,157.3,...,90,2bbl,2.97,3.23,9.40,68,5500,37,41,5572
porsche,3,186,gas,std,two,hatchback,rwd,front,94.5,168.9,...,151,mpfi,3.94,3.11,9.50,143,5500,19,27,22018
renault,0,?,gas,std,four,wagon,fwd,front,96.1,181.5,...,132,mpfi,3.46,3.90,8.70,?,?,23,31,9295
saab,3,150,gas,std,two,hatchback,fwd,front,99.1,186.6,...,121,mpfi,3.54,3.07,9.31,110,5250,21,28,11850
subaru,2,83,gas,std,two,hatchback,fwd,front,93.7,156.9,...,97,2bbl,3.62,2.36,9.00,69,4900,31,36,5118
toyota,1,87,gas,std,two,hatchback,fwd,front,95.7,158.7,...,92,2bbl,3.05,3.03,9.00,62,4800,35,39,5348
volkswagen,2,122,diesel,std,two,sedan,fwd,front,97.3,171.7,...,97,idi,3.01,3.40,23.00,52,4800,37,46,7775
volvo,-2,103,gas,std,four,sedan,rwd,front,104.3,188.8,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,12940

In [62]:
autoprice.groupby(['make'])[['city-mpg','highway-mpg']].mean().sort_values(by = 'city-mpg')

                city-mpg  highway-mpg
make
jaguar         14.333333    18.333333
porsche        17.400000    26.000000
mercedes-benz  18.500000    21.000000
audi           18.857143    24.142857
mercury        19.000000    24.000000
bmw            19.375000    25.375000
saab           20.333333    27.333333
alfa-romero    20.333333    26.666667
volvo          21.181818    25.818182
peugot         22.454545    26.636364
renault        23.000000    31.000000
mitsubishi     24.923077    31.153846
mazda          25.705882    31.941176
subaru         26.333333    30.750000
nissan         27.000000    32.944444
toyota         27.500000    32.906250
dodge          28.000000    34.111111
plymouth       28.142857    34.142857
volkswagen     28.583333    34.916667
honda          30.384615    35.461538
isuzu          31.000000    36.000000
chevrolet      41.000000    46.333333

In [64]:
autoprice.groupby(['make'])[['city-mpg','highway-mpg']].max().sort_values(by = 'city-mpg')

               city-mpg  highway-mpg
make
jaguar               15           19
mercury              19           24
porsche              19           28
saab                 21           28
alfa-romero          21           27
mercedes-benz        22           25
renault              23           31
bmw                  23           29
audi                 24           30
volvo                26           28
peugot               28           33
subaru               32           37
mazda                36           42
mitsubishi           37           41
dodge                37           41
plymouth             37           41
volkswagen           37           46
isuzu                38           43
toyota               38           47
nissan               45           50
chevrolet            47           53
honda                49           54

In [65]:
autoprice.groupby(['make','body-style'])[['city-mpg','highway-mpg']].max().sort_values(by = 'city-mpg')

                           city-mpg  highway-mpg
make          body-style
jaguar        sedan              15           19
audi          hatchback          16           22
mercedes-benz convertible        16           18
porsche       convertible        17           25
              hardtop            17           25
alfa-romero   hatchback          19           26
audi          wagon              19           25
mercury       hatchback          19           24
porsche       hatchback          19           28
alfa-romero   convertible        21           27
saab          sedan              21           28
              hatchback          21           28
mercedes-benz hardtop            22           25
              wagon              22           25
              sedan              22           25
bmw           sedan              23           29
renault       hatchback          23           31
              wagon              23           31
toyota        convertible        24           30
              hardtop            24           30
plymouth      wagon              24           30
volkswagen    convertible        24           29
              hatchback          24           29
volvo         wagon              24           28
dodge         wagon              24           30
audi          sedan              24           30
isuzu         hatchback          24           29
mitsubishi    sedan              25           32
volkswagen    wagon              25           31
peugot        wagon              25           25
volvo         sedan              26           28
peugot        sedan              28           33
subaru        wagon              28           32
honda         sedan              30           34
              wagon              30           34
nissan        hatchback          31           37
subaru        hatchback          31           36
dodge         sedan              31           38
mazda         hatchback          31           38
nissan        wagon              31           37
              hardtop            31           37
plymouth      sedan              31           38
toyota        wagon              31           37
subaru        sedan              32           37
mazda         sedan              36           42
volkswagen    sedan              37           46
mitsubishi    hatchback          37           41
dodge         hatchback          37           41
plymouth      hatchback          37           41
toyota        hatchback          38           47
              sedan              38           47
isuzu         sedan              38           43
chevrolet     sedan              38           43
nissan        sedan              45           50
chevrolet     hatchback          47           53
honda         hatchback          49           54

In [66]:
data_series1 = pd.Series([10,20,30,40,50])
data_series2 = pd.Series([100,200,300,400,500])

In [67]:
pd.concat([data_series1,data_series2], axis = 1)

    0    1
0  10  100
1  20  200
2  30  300
3  40  400
4  50  500