In [3]:
import numpy as np
import pandas as pd

####  a.	Read data from csv file fire department of New York City (FDNY)
####  b.	View content of the data

In [5]:
FDNY = pd.read_csv('FDNY.csv')
display(FDNY)

,FacilityName,FacilityAddress,Borough
0,FacilityName,FacilityAddress,Borough
1,Engine 4/Ladder 15,42 South Street,Manhattan
2,Engine 10/Ladder 10,124 Liberty Street,Manhattan
3,Engine 6,49 Beekman Street,Manhattan
4,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
...,...,...,...
214,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island
215,Engine 167/Ladder 87,345 Annadale Road,Staten Island
216,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island
217,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island
218,Engine 151/Ladder 76,7219 Amboy Road,Staten Island

###  c.	View first five records

In [6]:
FDNY.head()

,FacilityName,FacilityAddress,Borough
0,FacilityName,FacilityAddress,Borough
1,Engine 4/Ladder 15,42 South Street,Manhattan
2,Engine 10/Ladder 10,124 Liberty Street,Manhattan
3,Engine 6,49 Beekman Street,Manhattan
4,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan

###  d.	Skip the first row from dataset

In [8]:
FDNY = pd.read_csv('FDNY.csv', skiprows = 1)
display (FDNY)

,FacilityName,FacilityAddress,Borough
0,Engine 4/Ladder 15,42 South Street,Manhattan
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan
2,Engine 6,49 Beekman Street,Manhattan
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
4,Ladder 8,14 North Moore Street,Manhattan
...,...,...,...
213,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island
214,Engine 167/Ladder 87,345 Annadale Road,Staten Island
215,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island
216,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island
217,Engine 151/Ladder 76,7219 Amboy Road,Staten Island

### e.	View first five records from fixed dataset

In [9]:
FDNY.head()

,FacilityName,FacilityAddress,Borough
0,Engine 4/Ladder 15,42 South Street,Manhattan
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan
2,Engine 6,49 Beekman Street,Manhattan
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
4,Ladder 8,14 North Moore Street,Manhattan

### f.	Show statistics of dataset.

In [11]:
FDNY.describe()

              FacilityName  FacilityAddress   Borough
count                  218              218       218
unique                 218              218         5
top     Engine 4/Ladder 15  42 South Street  Brooklyn
freq                     1                1        66

###  g.	Display columns of the dataset

In [8]:
FDNY.columns

Index(['FacilityName', 'FacilityAddress', 'Borough'], dtype='object')

###  h.	View index of dataset

In [9]:
FDNY.index

RangeIndex(start=1, stop=219, step=1)

In [23]:
FDNY.dtypes

FacilityName       object
FacilityAddress    object
Borough            object
dtype: object

In [10]:
FDNY.shape

(218, 3)

###  i.	Find the total number of fire department facilities in New York city

In [29]:
FDNY['FacilityName'].unique().size

218

### j.	Find the total number of fire department facilities in each borough.

In [17]:
FDNY.groupby(['Borough']).size()

Borough
Bronx            34
Brooklyn         66
Manhattan        48
Queens           50
Staten Island    20
dtype: int64

### k.	Show size of FDNY information for each borough.

In [16]:
FDNY.groupby(['Borough']).size()

Borough
Bronx            34
Brooklyn         66
Manhattan        48
Queens           50
Staten Island    20
dtype: int64

### l.	Show all the department facilities in Manhattan (use group by)

In [19]:
FDNY.groupby('Borough').get_group("Manhattan")

,FacilityName,FacilityAddress,Borough
0,Engine 4/Ladder 15,42 South Street,Manhattan
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan
2,Engine 6,49 Beekman Street,Manhattan
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
4,Ladder 8,14 North Moore Street,Manhattan
5,Engine 9/Ladder 6,75 Canal Street,Manhattan
6,Engine 15/Ladder 18/Battalion 4,25 Pitt Street,Manhattan
7,Engine 28/Ladder 11,222 East 2nd Street,Manhattan
8,Engine 5,340 East 14th Street,Manhattan
9,Engine 55,363 Broome Street,Manhattan
10,Ladder 20/Division 1,253 Lafayette Street,Manhattan
11,Engine 24/Ladder 5/Battalion 2,227-29 6th Avenue,Manhattan
12,Engine 33/Ladder 9,42 Great Jones Street,Manhattan
13,Ladder 3/Battalion 6,108 East 13th Street,Manhattan
14,Squad 18,132 West 10th Street,Manhattan
15,Engine 34/Ladder 21,440 West 38th Street,Manhattan
16,Engine 26,220 West 37th Street,Manhattan
17,Engine 3/Ladder 12/Battalion 7,150 West 19th Street,Manhattan
18,Engine 1/Ladder 24,142-46 West 31st Street,Manhattan
19,Engine 14,14 East 18th Street,Manhattan
20,Engine 16 / Ladder 7,234 East 29th Street,Manhattan
21,Engine 21,238 East 40th Street,Manhattan
22,Engine 54/Ladder 4/Battalion 9,782 8th Avenue,Manhattan
23,Engine 23,215 West 58th Street,Manhattan
24,Rescue 1,530 West 43rd Street,Manhattan
25,Engine 40/Ladder 35,131 Amsterdam Avenue,Manhattan
26,Ladder 25/District Office 4/Division 3,205-207 West 77th Street,Manhattan
27,Engine 74,120 West 83rd Street,Manhattan
28,Engine 65,33 West 43rd Street,Manhattan
29,Engine 8 / Ladder 2 / Battalion 8,167 East 51st Street,Manhattan
30,Engine 39/Ladder 16,157-59 East 67th Street,Manhattan
31,Engine 44,221 East 75th Street,Manhattan
32,Engine 22/Ladder 13/Battalion 10,159 East 85th Street,Manhattan
33,Engine 58/Ladder 26,1367 5th Avenue,Manhattan
34,Engine 53/Ladder 43,1836-46 3rd Avenue,Manhattan
35,Engine 91,242 East 111th Street,Manhattan
36,Engine 35/Ladder 14,2282 3rd Avenue,Manhattan
37,Engine 76/Ladder 22/Battalion 11,145-51 West 100th Street,Manhattan
38,Engine 47,502 West 113th Street,Manhattan
39,Engine 59/Ladder 30,111 West 133rd Street,Manhattan
40,Engine 37/Ladder 40,415 West 125th Street,Manhattan
41,Engine 69/Ladder 28/Battalion 16,248 West 143rd Street,Manhattan
42,Engine 80/Ladder 23,503 West 139th Street,Manhattan
43,Engine 84/Ladder 34,513 West 161st Street,Manhattan
44,Engine 67,518 West 170th Street,Manhattan
45,Engine 93/Ladder 45/Battalion 13,515 West 181st Street,Manhattan
46,Engine 95/Ladder 36,29 Vermilyea Avenue,Manhattan
47,Marine 1,Little West 12th Street/Hudson River,Manhattan

### m.	Clean the dataset and drop null/nan value.

In [19]:
FDNY.dropna(inplace = True)
FDNY

,FacilityName,FacilityAddress,Borough
1,Engine 4/Ladder 15,42 South Street,Manhattan
2,Engine 10/Ladder 10,124 Liberty Street,Manhattan
3,Engine 6,49 Beekman Street,Manhattan
4,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
5,Ladder 8,14 North Moore Street,Manhattan
...,...,...,...
214,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island
215,Engine 167/Ladder 87,345 Annadale Road,Staten Island
216,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island
217,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island
218,Engine 151/Ladder 76,7219 Amboy Road,Staten Island